build:
  quality:
    job:
      build-analysis:
        machine: grabl-ubuntu-2004
        script: |
          SONARCLOUD_CODE_ANALYSIS_CREDENTIAL=$SONARCLOUD_CREDENTIAL \
            bazel run @graknlabs_dependencies//tool/sonarcloud:code-analysis -- \
            --project-key graknlabs_graql --branch=$GRABL_BRANCH --commit-id=$GRABL_COMMIT
  correctness:
    jobs:
      build:
        machine: grabl-ubuntu-2004
        script: |
          curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/rbe.sh
          sudo mkdir -p /home/grabl/.credentials/ && sudo chmod a+w /home/grabl/.credentials/ && bash ./rbe.sh && rm ./rbe.sh
          bazel build --config=rbe //...
          bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
          bazel test --config=rbe $(bazel query 'kind(checkstyle_test, //...)')
      build-dependency:
        machine: grabl-ubuntu-2004
        script: |
          dependencies/maven/update.sh
          git diff --exit-code dependencies/maven/artifacts.snapshot
          bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
      test-graql-java:
        machine: grabl-ubuntu-2004
        script: |
          curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/rbe.sh
          sudo mkdir -p /home/grabl/.credentials/ && sudo chmod a+w /home/grabl/.credentials/ && bash ./rbe.sh && rm ./rbe.sh
          bazel test --config=rbe //java/... --test_output=errors
      deploy-maven-snapshot:
        machine: grabl-ubuntu-2004
        script: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //grammar:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java/common:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java/pattern:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java/query:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java/parser:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java:deploy-maven -- snapshot
      test-deployment-maven:
        machine: grabl-ubuntu-2004
        script: |
          sed -i -e "s/GRAQL_LANG_VERSION_MARKER/$GRABL_COMMIT/g" java/test/deployment/pom.xml
          cd java/test/deployment/ && mvn test
    execution:
      - build
      - build-dependency
      - test-graql-java
      - deploy-maven-snapshot:
          depends: [build, build-dependency, test-graql-java]
      - test-deployment-maven:
          depends: [deploy-maven-snapshot]

release:
  validation:
    job:
      validate-dependencies:
        machine: grabl-ubuntu-2004
        script: |
          bazel run @graknlabs_dependencies//tool/release:validate-deps -- @graknlabs_common
  deployment:
    jobs:
      deploy-github:
        machine: grabl-ubuntu-2004
        script: |
          pip install certifi
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tool/release:create-notes -- graql $(cat VERSION) ./RELEASE_TEMPLATE.md
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
          bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
      deploy-maven-release:
        machine: grabl-ubuntu-2004
        script: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(cat VERSION) //grammar:deploy-maven -- release
          bazel run --define version=$(cat VERSION) //java:deploy-maven -- release
    execution:
      - deploy-github
      - deploy-maven-release
